### ISSUE TITLE
Syntax error for return type of ConfigFile class constructor

### ISSUE THREAD

**Issue by TimKindervatter** [TimKindervatter/AccuRT-Driver#1]
When importing the ConfigFile class, a syntax error occurs wherein the syntax for denoting the return type is not recognized (->). This may have to do with the version of Python that is being used. Possible fix is to simply remove this explicit return type so that older versions of Python are supported.

Example error message:

Traceback (most recent call last):
  File "accurt_driver.py", line 14, in <module>
    from ConfigFile import *
  File "/export/home/timothy/svn/c-disort/trunk/python/accurt_driver/src/ConfigFile.py", line 2
    def __init__(self, template_config_name, clone_config_name) -> None:

**Comment by TimKindervatter** [comment]
Appears to be dependent on Python version. Issue occurs when using Python 2.
